CreationDate = 2024-08-13T12:09:27.285865
camera_count = 5

[cam_1]
port = 1
rotation_count = 0
error = 0.12
exposure = "null"
grid_count = 100
size = [1456, 1088]
matrix = [[1784.3009971031029, 0.0, 752.5078625953878], [0.0, 1788.4002123141331, 506.3309604431838], [0.0, 0.0, 1.0]]
distortions = [-0.49785674204295766, 0.3171834782490962, -0.00022853389647007117, -0.0006269068607599847, -0.12773688586894644]
translation = [0.3909052870391961, 0.3696005822530934, 0.12578742991224418]
rotation = [-0.012141552546692316, -0.4672032507048539, 1.4651982744511383]

[cam_2]
port = 2
rotation_count = 0
error = 0.114
exposure = "null"
grid_count = 100
size = [1456, 1088]
matrix = [[1789.3107470239331, 0.0, 731.9219668882813], [0.0, 1793.2512790517499, 520.2876917182408], [0.0, 0.0, 1.0]]
distortions = [-0.49032513477855816, 0.2510662958760789, -0.0010416992726537816, 0.000928996426213488, 0.01952788917576716]
translation = [0.27214620630763636, 0.6478261522066371, 0.21102751785965068]
rotation = [0.0009234129720962298, -0.7149466320126622, 2.2168173259750668]

[cam_3]
port = 3
rotation_count = 0
error = 0.105
exposure = "null"
grid_count = 100
size = [1456, 1088]
matrix = [[1790.7406557987165, 0.0, 711.739214348308], [0.0, 1793.8377926620042, 539.1521884977357], [0.0, 0.0, 1.0]]
distortions = [-0.5041194928630861, 0.3354804007395974, -0.001207734638885515, -0.0007521793702576436, -0.13681936019942836]
translation = [-0.2947000687120463, 0.6410614300347597, 0.21165104091100545]
rotation = [-0.010241392947713514, 0.730926464683386, -2.2327157654881953]

[cam_4]
port = 4
rotation_count = 0
error = 0.117
exposure = "null"
grid_count = 100
size = [1456, 1088]
matrix = [[1785.8765518790572, 0.0, 730.0725522457836], [0.0, 1789.5105114823505, 536.2171163100587], [0.0, 0.0, 1.0]]
distortions = [-0.5029821458335525, 0.3695202622921604, 0.0011067719096286145, -0.00002513681826917908, -0.2625909929788929]
translation = [-0.2862978577143054, 0.10378832876571861, 0.03157813803022864]
rotation = [0.015282565445267736, 0.23898400913567516, -0.7496087577504105]

[cam_5]
port = 5
rotation_count = 0
error = 0.118
exposure = "null"
grid_count = 100
size = [1456, 1088]
matrix = [[1783.6243153917467, 0.0, 734.4007023079157], [0.0, 1787.281263780255, 522.1849599871903], [0.0, 0.0, 1.0]]
distortions = [-0.5306243302319483, 0.5758281732200565, -0.00022650086979637157, -0.0007272720243103321, -0.77548611423538]
translation = [0.0, 0.00005954710971643587, 0.0000664931516981153]
rotation = [0.00013896434463847463, 0.000011695195098498706, 0.00017846617304232074]

[capture_volume]
stage = 2
origin_sync_index = "null"

[charuco]
columns = 6
rows = 8
board_height = 25.6
board_width = 19.2
dictionary = "DICT_4X4_50"
units = "cm"
aruco_scale = 0.75
square_size_overide_cm = 3.2
inverted = false

[stereo_1_2]
RMSE = 0.6114095342831499
rotation = [[0.7070679929045423, -0.6765301369087042, -0.2058198903513271], [0.674992465597462, 0.7324656940121498, -0.08876473670303436], [0.21080802830205828, -0.07616417103592688, 0.974555793299598]]
translation = [[0.2718602955953859], [0.1192938871451428], [0.035964908256043565]]

[stereo_1_3]
RMSE = 0.7079562486743907
rotation = [[-0.7351592433430935, -0.6477473305477354, -0.19991068679661234], [0.6446342104955795, -0.5767613854739836, -0.5017898353742051], [0.20973226167175918, -0.49776470344371926, 0.8415715527628265]]
translation = [[0.26376726453934957], [0.6653108064114415], [0.2078910070716375]]

[stereo_1_4]
RMSE = 0.45143694800996387
rotation = [[-0.6850756327178321, 0.6994549227959279, 0.2035538956463487], [-0.6868827372467738, -0.5271705248515964, -0.5002832627622794], [-0.24261797692801215, -0.4825495297938182, 0.8415951928136973]]
translation = [[-0.2999137465800284], [0.6287374800514274], [0.2010962024467876]]

[stereo_1_5]
RMSE = 0.48470206263358373
rotation = [[0.03324752102874493, 0.9521406860004157, 0.3038465343032585], [-0.9498423718562107, 0.12468945955823235, -0.2867961075427003], [-0.31095670272887077, -0.2790710532064084, 0.9085291829601596]]
translation = [[-0.4113534749318645], [0.36076405519008103], [0.11152760727930554]]

[stereo_2_3]
RMSE = 0.710578198735839
rotation = [[-0.03910574455996199, -0.9523766143487293, -0.30240622543866785], [0.9480968302167618, 0.06021145016941251, -0.31222905342300344], [0.31556796617422916, -0.29892033338357515, 0.9005906356466915]]
translation = [[0.4014498459046658], [0.4133005789666195], [0.12845223094257013]]

[stereo_2_4]
RMSE = 0.5229782034992623
rotation = [[-0.9995205264719433, 0.030862454513261, 0.0024952079404485135], [-0.026314729902567592, -0.8042339218637896, -0.5937300176963792], [-0.016317234796499575, -0.5935110005930849, 0.8046604501425378]]
translation = [[-0.03386073591737979], [0.7553870666619937], [0.24720776793922333]]

[stereo_2_5]
RMSE = 0.5262043377315748
rotation = [[-0.6844221413196455, 0.6944175837098892, 0.22214984111169217], [-0.6930870941566429, -0.5251305133494006, -0.4938301568990045], [-0.2262666842134115, -0.4919574812764959, 0.8407028156436457]]
translation = [[-0.30663831489880594], [0.6365577424790254], [0.19794389610922325]]

[stereo_3_4]
RMSE = 0.527966756031524
rotation = [[0.010230967578946723, -0.9477794805596794, -0.3187622680500671], [0.9441270603629895, 0.11417444713173025, -0.3091735588832003], [0.3294228607621798, -0.2977889384315475, 0.8959923699201202]]
translation = [[0.3915309623052215], [0.37630544612257094], [0.12396074174995786]]

[stereo_3_5]
RMSE = 0.7620877572934013
rotation = [[-0.6979224203147232, -0.6828002487444104, -0.21607432873113347], [0.6797284409847087, -0.5365191205316395, -0.5001164662560642], [0.2255516387405242, -0.49591436117390975, 0.8385674717295774]]
translation = [[0.2750415454022394], [0.643280410216499], [0.2062569931947221]]

[stereo_4_5]
RMSE = 1.154382496080321
rotation = [[0.7061615919002047, -0.6744003230620835, -0.21568497949260676], [0.6775019412294453, 0.7320931614066515, -0.07092758738282098], [0.2057350863496599, -0.09604065428438047, 0.9738836003185012]]
translation = [[0.27333471968086404], [0.11885826814361804], [0.03950113518419939]]
